#! /bin/sh

#####################################################
#   ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗   #
#   ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║   #
#   ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║   #
#   ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║   #
#   ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║   #
#   ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝   #                                    
##################### By: nizur #####################

#####################################################
# AutoStart                                         #
#####################################################

$HOME/.config/polybar/launch.sh
pgrep -x redshift > /dev/null || redshift &
pgrep -x sxhkd > /dev/null || sxhkd &
dunst --config $HOME/.config/dunst/dunstrc &
picom -b --experimental-backends --config $HOME/.config/picom/picom.conf &
xsetroot -cursor_name left_ptr &
xrdb --merge $HOME/.Xresources &
feh --bg-fill -r -z $HOME/Pictures/Wallpapers/catpuccin/*

#####################################################
# Functions                                         #
#####################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

#####################################################
# Workspaces                                        #
#####################################################

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

#####################################################
# Looks                                             #
#####################################################

config border_width             2
config border_radius            3
config window_gap               5
config top_padding              0
config bottom_padding           30
config split_ratio              0.5

config active_border_color      "#F38BA8"
config focused_border_color     "#A6E3A1"
config normal_border_color      "#1E1E2E"

config click_to_focus           true 
#config focus_follows_pointer    true
config borderless_monocle       true
config gapless_monocle          false

#####################################################
# Rules                                             #
#####################################################

rule firefox    desktop='^1'
rule Code       desktop='^2'
rule discord    desktop='^5'
rule Gimp-2.10  desktop='^8' state=floating follow=on
rule kitty      follow=on focus=on
rule feh        state=floating

#####################################################
# Touchpad                                          #
#####################################################

#xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
#xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
