#! /bin/sh

# AutoStart
pgrep -x sxhkd > /dev/null || sxhkd &
picom -b --experimental-backends &
xsetroot -cursor_name left_ptr &
xrdb --merge $HOME/.Xresources &
feh --bg-fill --randomize $HOME/Pictures/Wallpapers/* &
$HOME/.config/polybar/launch.sh

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Looks
bspc config border_width            1
bspc config border_radius           3
bspc config window_gap              8

bspc config focus_follows_pointer	true
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

# Window rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^1'
bspc rule -a Code desktop='^2'
